perf tools: Initialize perf_data_file fd field
Building the perf CTF converter fails with gcc 4.8.4
on Ubuntu 14.04 with the following error:

error: missing initializer for field ‘fd’ of ‘struct perf_data_file’
[-Werror=missing-field-initializers]

Per 4b838b0d and the ensuing discussion on the mailing
list, it appears that this affects other distributions
and gcc versions.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Cc: Jiri Olsa <jolsa@kernel.org>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Ingo Molnar <mingo@redhat.com>
Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>